### ISSUE TITLE
unexpected 'require' (T_REQUIRE), expecting identifier (T_STRING)

### ISSUE THREAD

**Issue by strausmann** [kabachello/ComposerApi#3]
With PHP 5.6 i got this error message.

`Parse error: syntax error, unexpected 'require' (T_REQUIRE), expecting identifier (T_STRING) in ComposerAPI.php on line 203
`
Unfortunately, I have no idea how to fix this.

Regards,
Bjoern

**Comment by kabachello** [comment]
It seems, that your version of PHP takes the method name "require" as a reserved keyword. Unfortunately, I do not have a PHP 5.6 server to test on, but on PHP 7+ it does not cause any problems. If needed, you can try to change the name of the method to anything you like. Nothing depends on that method, so you are free to change it's name.

**Comment by strausmann** [comment]
Thank you for the feedback
